Repository Prography-8th-team8/team8-BE, pull requests merged in 2023-06, with the labels that each got.

#25 feat(store): 블로그 api 분리 및 JavaDOC 적용
  src/main/java/prography/cakeke/server/store/adpter/in/web/StoreController.java
  src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreBlogResponse.java
  src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreDetailResponse.java
  src/main/java/prography/cakeke/server/store/adpter/out/external/NaverSearchApiAdapter.java
  src/main/java/prography/cakeke/server/store/application/port/in/StoreUseCase.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadNaverSearchApiPort.java
  src/main/java/prography/cakeke/server/store/application/service/StoreService.java
Labels: feature, style

#28 refactor(store): store 상세 조회시, store 단건 조회로 쿼리 수정
  src/main/java/prography/cakeke/server/CakekeApplication.java
  src/main/java/prography/cakeke/server/store/adpter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadStorePort.java
  src/main/java/prography/cakeke/server/store/application/service/StoreService.java
  src/main/java/prography/cakeke/server/store/domain/StoreTag.java
Labels: refactor

#33 Refactor store
  src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreDetailResponse.java
  src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreResponse.java
  src/main/java/prography/cakeke/server/store/adpter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/domain/Store.java
Labels: feature

#34 feat(image): 이미지 업로드 api 구현 및 테스트 완료 #29
  build.gradle
  src/main/java/prography/cakeke/server/config/AwsS3Config.java
  src/main/java/prography/cakeke/server/image/adapter/in/web/ImageController.java
  src/main/java/prography/cakeke/server/image/adapter/in/web/response/UploadImageResponse.java
  src/main/java/prography/cakeke/server/image/application/port/in/ImageUseCase.java
  src/main/java/prography/cakeke/server/image/application/port/out/.gitkeep
  src/main/java/prography/cakeke/server/image/application/service/ImageService.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/StoreController.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/response/DistrictCountResponse.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/response/StoreBlogResponse.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/response/StoreDetailResponse.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/response/StoreNaverBlogSearchApiResponse.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/response/StoreNaverLocalSearchApiResponse.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/response/StoreResponse.java
  src/main/java/prography/cakeke/server/store/adapter/out/external/NaverSearchApiAdapter.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StoreAndTagRepository.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StoreRepository.java
  src/main/java/prography/cakeke/server/store/application/port/in/StoreUseCase.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadNaverSearchApiPort.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadStorePort.java
  src/main/java/prography/cakeke/server/store/application/service/StoreService.java
  src/main/java/prography/cakeke/server/store/domain/City.java
  src/main/java/prography/cakeke/server/store/domain/Store.java
  src/main/resources/application.yml
Labels: feature

#35 admin: store에 image 올리기
  build.gradle
  src/main/java/prography/cakeke/server/admin/adapter/in/web/AdminController.java
  src/main/java/prography/cakeke/server/admin/application/port/in/AdminUseCase.java
  src/main/java/prography/cakeke/server/admin/application/service/AdminService.java
  src/main/java/prography/cakeke/server/common/domain/Core.java
  src/main/java/prography/cakeke/server/config/error/BaseException.java
  src/main/java/prography/cakeke/server/config/error/ErrorCode.java
  src/main/java/prography/cakeke/server/config/error/ErrorResponse.java
  src/main/java/prography/cakeke/server/config/error/GlobalExceptionHandler.java
  src/main/java/prography/cakeke/server/image/adaper/in/web/ImageExceptionController.java
  src/main/java/prography/cakeke/server/image/adapter/in/web/ImageController.java
  src/main/java/prography/cakeke/server/image/adapter/in/web/response/UploadImageResponse.java
  src/main/java/prography/cakeke/server/image/application/port/in/ImageUseCase.java
  src/main/java/prography/cakeke/server/image/application/service/ImageService.java
  src/main/java/prography/cakeke/server/image/exceptions/InvalidFileNameException.java
  src/main/java/prography/cakeke/server/image/exceptions/NotSupportedFileFormatException.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/StoreController.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/StoreExceptionController.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/response/StoreDetailResponse.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/response/StoreResponse.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StoreRepository.java
  src/main/java/prography/cakeke/server/store/application/port/in/StoreUseCase.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadStorePort.java
  src/main/java/prography/cakeke/server/store/application/service/StoreService.java
  src/main/java/prography/cakeke/server/store/domain/Store.java
  src/main/java/prography/cakeke/server/store/domain/StoreAndTag.java
  src/main/java/prography/cakeke/server/store/domain/StoreTag.java
  src/main/java/prography/cakeke/server/store/exceptions/NotFoundStoreException.java
Labels: feature, refactor

#38 화면 좌표로 가게 재검색 API 구현
  src/main/java/prography/cakeke/server/store/adapter/in/web/StoreController.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/StoreExceptionController.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/application/port/in/StoreUseCase.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadStorePort.java
  src/main/java/prography/cakeke/server/store/application/service/StoreService.java
  src/main/java/prography/cakeke/server/store/exceptions/NotAllowedLocationException.java
Labels: feature

#41 가게 리스트 조회시, 케이크 카테고리 필터링 추가 #40
  src/main/java/prography/cakeke/server/store/adapter/in/web/StoreController.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/application/port/in/StoreUseCase.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadStorePort.java
  src/main/java/prography/cakeke/server/store/application/service/StoreService.java
  src/main/java/prography/cakeke/server/store/domain/StoreType.java
Labels: feature

#43 Comment admin image
  src/main/java/prography/cakeke/server/admin/application/service/AdminService.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/domain/Store.java
Labels: style, comment

#45 Feature/admin 카테고리 변경
  src/main/java/prography/cakeke/server/admin/adapter/in/web/AdminController.java
  src/main/java/prography/cakeke/server/admin/application/port/in/AdminUseCase.java
  src/main/java/prography/cakeke/server/admin/application/service/AdminService.java
  src/main/java/prography/cakeke/server/common/domain/Core.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StoreAndTagRepository.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StoreTagRepository.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadStorePort.java
  src/main/java/prography/cakeke/server/store/application/port/out/SaveStorePort.java
  src/main/java/prography/cakeke/server/store/domain/Store.java
  src/main/java/prography/cakeke/server/store/domain/StoreAndTag.java
Labels: feature
