Repository Prography-8th-team8/team8-BE, pull requests merged in 2023-07, with the labels that each got.

#47 refactor(admin): 케이크샵 category 변경 기능 성능 개선 #46
  src/main/java/prography/cakeke/server/admin/application/service/AdminService.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StoreAndTagRepository.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/application/port/out/DeleteStorePort.java
  src/main/java/prography/cakeke/server/store/domain/Store.java
  src/main/java/prography/cakeke/server/store/domain/StoreAndTag.java
  src/main/java/prography/cakeke/server/store/domain/StoreType.java
Labels: refactor

#48 fix(store): 카테고리 타입 추가
  src/main/java/prography/cakeke/server/store/domain/StoreType.java
Labels: fix

#49 refactor(image): image service 종속성 분리 #42
  src/main/java/prography/cakeke/server/image/adaper/out/AwsS3Adapter.java
  src/main/java/prography/cakeke/server/image/application/service/ImageService.java
  src/main/java/prography/cakeke/server/store/application/port/out/UploadS3Port.java
Labels: refactor

#50 test(store): StoreService 단위 테스트 및 통합 테스트 전체 구현
  src/main/java/prography/cakeke/server/store/application/service/StoreService.java
  src/test/java/prography/cakeke/server/common/BaseTest.java
  src/test/java/prography/cakeke/server/store/application/service/StoreServiceTest.java
  src/test/resources/application.yml
Labels: feature, test

#51 refactor(store): store list 조회 api를 store 조회 api, store type 조회 api로 분리
  src/main/java/prography/cakeke/server/store/adapter/in/web/StoreController.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/response/StoreTagResponse.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/application/port/in/StoreUseCase.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadStorePort.java
  src/main/java/prography/cakeke/server/store/application/service/StoreService.java
  src/test/java/prography/cakeke/server/store/application/service/StoreServiceTest.java
Labels: refactor

#54 Feature store feed #53
  src/main/java/prography/cakeke/server/admin/adapter/in/web/AdminController.java
  src/main/java/prography/cakeke/server/admin/application/service/AdminService.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/StoreController.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/StoreExceptionController.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/response/FeedImageResponse.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StoreTagRepository.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadStorePort.java
  src/main/java/prography/cakeke/server/store/domain/Store.java
  src/main/java/prography/cakeke/server/store/exceptions/NotFoundStoreTagException.java
Labels: feature

#55 store 서비스 new 코드 컨트롤러로 이동
  src/main/java/prography/cakeke/server/store/adapter/in/web/StoreController.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/application/port/in/StoreUseCase.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadStorePort.java
  src/main/java/prography/cakeke/server/store/application/service/StoreService.java
  src/test/java/prography/cakeke/server/common/BaseMock.java
  src/test/java/prography/cakeke/server/store/application/service/StoreServiceTest.java
Labels: refactor, test

#56 refactor(store): district 별로 가게 갯수 조회시, querydsl에서 response를 조회하지 않도록 변경
  src/main/java/prography/cakeke/server/store/adapter/in/web/StoreController.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/response/DistrictCountDTO.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/response/StoreNaverLocalSearchApiResponse.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/application/port/in/StoreUseCase.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadStorePort.java
  src/main/java/prography/cakeke/server/store/application/service/StoreService.java
Labels: refactor

#57 refactor(store): feed 조회 api를 완전 랜덤으로 변경 #53
  src/main/java/prography/cakeke/server/store/adapter/in/web/StoreController.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/response/FeedImageResponse.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StorePersistenceAdapter.java
Labels: refactor

#58 refactor(store): StoreResponse Store로 변경
  src/main/java/prography/cakeke/server/store/adapter/in/web/StoreController.java
  src/main/java/prography/cakeke/server/store/adapter/in/web/response/StoreDetailResponse.java
  src/main/java/prography/cakeke/server/store/adapter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/application/port/in/StoreUseCase.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadStorePort.java
  src/main/java/prography/cakeke/server/store/application/service/StoreService.java
  src/test/java/prography/cakeke/server/store/application/service/StoreServiceTest.java
Labels: refactor
