Repository Prography-8th-team8/team8-BE, pull requests merged in 2023-05, with the labels that each got.

#3 Chore/ CI-CD
  Dockerfile
  build.gradle
  src/main/java/prography/cakeke/server/marker/adpter/in/web/.gitkeep
  src/main/java/prography/cakeke/server/marker/adpter/out/persistence/.gitkeep
  src/main/java/prography/cakeke/server/marker/application/port/in/.gitkeep
  src/main/java/prography/cakeke/server/marker/application/port/out/.gitkeep
  src/main/java/prography/cakeke/server/marker/domain/City.java
  src/main/java/prography/cakeke/server/marker/domain/District.java
  src/main/java/prography/cakeke/server/marker/domain/Marker.java
Labels: chore

#8 Chore/Jasypt
  build.gradle
  src/main/java/prography/cakeke/server/config/JasyptConfig.java
  src/main/resources/application.yml
Labels: chore

#5 Chore/Swagger
  build.gradle
Labels: chore

#9 Chore/Jasypt-2
  build.gradle
Labels: bug, chore

#10 Chore/Jasypt-3
  src/main/resources/application.yml
Labels: bug, chore

#12 Feature/entity 생성
  src/main/java/prography/cakeke/server/common/Core.java
  src/main/java/prography/cakeke/server/store/adpter/in/web/.gitkeep
  src/main/java/prography/cakeke/server/store/adpter/in/web/StoreResponse.java
  src/main/java/prography/cakeke/server/store/domain/City.java
  src/main/java/prography/cakeke/server/store/domain/District.java
  src/main/java/prography/cakeke/server/store/domain/Store.java
  src/main/java/prography/cakeke/server/store/domain/StoreAndTag.java
  src/main/java/prography/cakeke/server/store/domain/StoreTag.java
Labels: feature

#14 Feature store list
  build.gradle
  src/main/java/prography/cakeke/server/config/QuerydslConfig.java
  src/main/java/prography/cakeke/server/store/adpter/in/web/StoreController.java
  src/main/java/prography/cakeke/server/store/adpter/in/web/response/DistrictCountResponse.java
  src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreResponse.java
  src/main/java/prography/cakeke/server/store/adpter/out/persistence/.gitkeep
  src/main/java/prography/cakeke/server/store/adpter/out/persistence/StoreAndTagPersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/adpter/out/persistence/StoreAndTagRepository.java
  src/main/java/prography/cakeke/server/store/adpter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/adpter/out/persistence/StoreRepository.java
  src/main/java/prography/cakeke/server/store/application/port/in/.gitkeep
  src/main/java/prography/cakeke/server/store/application/port/in/StoreUseCase.java
  src/main/java/prography/cakeke/server/store/application/port/out/.gitkeep
  src/main/java/prography/cakeke/server/store/application/port/out/LoadStoreAndTagPort.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadStorePort.java
  src/main/java/prography/cakeke/server/store/application/service/StoreService.java
  src/main/java/prography/cakeke/server/store/domain/Store.java
  src/main/java/prography/cakeke/server/store/domain/StoreTag.java
Labels: feature, chore

#16 Refactor store list
  build.gradle
  src/main/java/prography/cakeke/server/config/QuerydslConfig.java
  src/main/java/prography/cakeke/server/store/adpter/in/web/StoreController.java
  src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreResponse.java
  src/main/java/prography/cakeke/server/store/adpter/out/persistence/StoreAndTagPersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/adpter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadStoreAndTagPort.java
  src/main/java/prography/cakeke/server/store/application/service/StoreService.java
  src/main/java/prography/cakeke/server/store/domain/Store.java
Labels: refactor

#17 Feature store list id (detail)
  src/main/java/prography/cakeke/server/store/adpter/in/web/StoreController.java
  src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreDetailResponse.java
  src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreNaverSearchApiResponse.java
  src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreResponse.java
  src/main/java/prography/cakeke/server/store/adpter/out/external/NaverSearchApiAdapter.java
  src/main/java/prography/cakeke/server/store/adpter/out/persistence/StorePersistenceAdapter.java
  src/main/java/prography/cakeke/server/store/application/port/in/StoreUseCase.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadNaverSearchApiPort.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadStorePort.java
  src/main/java/prography/cakeke/server/store/application/service/StoreService.java
  src/main/resources/application.yml
Labels: feature

#23 feat(store): store에 location 추가
  src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreDetailResponse.java
  src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreResponse.java
  src/main/java/prography/cakeke/server/store/domain/Store.java
Labels: feature

#20 Feature store blog (Integration with list)
  build.gradle
  src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreDetailResponse.java
  src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreNaverBlogSearchApiResponse.java
  src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreNaverLocalSearchApiResponse.java
  src/main/java/prography/cakeke/server/store/adpter/out/external/NaverSearchApiAdapter.java
  src/main/java/prography/cakeke/server/store/application/port/out/LoadNaverSearchApiPort.java
  src/main/java/prography/cakeke/server/store/application/service/StoreService.java
  src/main/resources/application.yml
Labels: feature
